Repository SU-SWS/stanford_person, pull requests merged in 2020-06, with the labels that each got.

#91 D8CORE-1736 Migration support for person importer
  composer.json
  modules/stanford_person_importer/config/install/config_pages.type.stanford_person_importer.yml
  modules/stanford_person_importer/config/install/core.entity_form_display.config_pages.stanford_person_importer.default.yml
  modules/stanford_person_importer/config/install/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  modules/stanford_person_importer/config/install/core.entity_view_display.config_pages.stanford_person_importer.default.yml
  modules/stanford_person_importer/config/install/core.entity_view_display.taxonomy_term.cap_org_codes.default.yml
  modules/stanford_person_importer/config/install/encrypt.profile.stanford_real_aes.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_cap_password.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_cap_username.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_orgs.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_sunetid.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_workgroup.yml
  modules/stanford_person_importer/config/install/field.field.node.stanford_person.su_person_profile_link.yml
  modules/stanford_person_importer/config/install/field.field.taxonomy_term.cap_org_codes.su_cap_org_code.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_cap_password.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_cap_username.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_orgs.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_sunetid.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_workgroup.yml
  modules/stanford_person_importer/config/install/field.storage.node.su_person_profile_link.yml
  modules/stanford_person_importer/config/install/field.storage.taxonomy_term.su_cap_org_code.yml
  modules/stanford_person_importer/config/install/key.key.stanford_encryption.yml
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person_importer/config/install/migrate_plus.migration_group.su_stanford_person.yml
  modules/stanford_person_importer/config/install/taxonomy.vocabulary.cap_org_codes.yml
  modules/stanford_person_importer/config/install/ultimate_cron.job.stanford_migrate_su_stanford_person.yml
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/src/CapInterface.php
  modules/stanford_person_importer/src/Config/ConfigOverrides.php
  modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person_importer/stanford_person_importer.install
  modules/stanford_person_importer/stanford_person_importer.module
  modules/stanford_person_importer/stanford_person_importer.services.yml
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
  modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
  stanford_person.info.yml
  tests/codeception/acceptance/StanfordPersonImporterCest.php
Labels: backend, patch, size/l

#93 "8.x-1.x > 8.1.1
  CHANGELOG.md
  composer.json
  modules/stanford_person_importer/config/install/config_pages.type.stanford_person_importer.yml
  modules/stanford_person_importer/config/install/core.entity_form_display.config_pages.stanford_person_importer.default.yml
  modules/stanford_person_importer/config/install/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  modules/stanford_person_importer/config/install/core.entity_view_display.config_pages.stanford_person_importer.default.yml
  modules/stanford_person_importer/config/install/core.entity_view_display.taxonomy_term.cap_org_codes.default.yml
  modules/stanford_person_importer/config/install/encrypt.profile.stanford_real_aes.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_cap_password.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_cap_username.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_orgs.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_sunetid.yml
  modules/stanford_person_importer/config/install/field.field.config_pages.stanford_person_importer.su_person_workgroup.yml
  modules/stanford_person_importer/config/install/field.field.node.stanford_person.su_person_profile_link.yml
  modules/stanford_person_importer/config/install/field.field.taxonomy_term.cap_org_codes.su_cap_org_code.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_cap_password.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_cap_username.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_orgs.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_sunetid.yml
  modules/stanford_person_importer/config/install/field.storage.config_pages.su_person_workgroup.yml
  modules/stanford_person_importer/config/install/field.storage.node.su_person_profile_link.yml
  modules/stanford_person_importer/config/install/field.storage.taxonomy_term.su_cap_org_code.yml
  modules/stanford_person_importer/config/install/key.key.stanford_encryption.yml
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person_importer/config/install/migrate_plus.migration_group.su_stanford_person.yml
  modules/stanford_person_importer/config/install/taxonomy.vocabulary.cap_org_codes.yml
  modules/stanford_person_importer/config/install/ultimate_cron.job.stanford_migrate_su_stanford_person.yml
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/src/CapInterface.php
  modules/stanford_person_importer/src/Config/ConfigOverrides.php
  modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person_importer/stanford_person_importer.install
  modules/stanford_person_importer/stanford_person_importer.module
  modules/stanford_person_importer/stanford_person_importer.services.yml
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
  modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
  stanford_person.info.yml
  tests/codeception/acceptance/StanfordPersonImporterCest.php
Labels: backend, patch, size/l

#96 D8CORE-2070: fixing and making the MS spacing consistent on accelerant headers
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs

#97 D8CORE-2049: change telephone to contact
  config/install/core.entity_view_display.node.stanford_person.default.yml
  config/install/field.field.node.stanford_person.su_person_profile_link.yml
  config/install/field.storage.node.su_person_profile_link.yml
Labels: size/xs

#94 D8CORE-2099: Required fields and default profile image.
  config/install/field.field.node.stanford_person.su_person_first_name.yml
  config/install/field.field.node.stanford_person.su_person_last_name.yml
  config/install/field.field.node.stanford_person.su_person_photo.yml
  config/install/field.field.node.stanford_person.su_person_short_title.yml
  content/file/4d5dde7e-f2c7-4d27-8ad1-99623b1308f8.json
  content/media/a4660e7f-d4bf-4a28-8030-9dc8576b1c9a.json
  lib/assets/img/stanford-person-default-profile-image.png
  stanford_person.install
  stanford_person.module
  stanford_person.post_update.php
  tests/codeception/acceptance/StanfordPersonCest.php
Labels: backend, size/s
