Repository SU-SWS/stanford_person, pull requests merged in 2020-10, with the labels that each got.

#116 8.1.7
  CHANGELOG.md
  config/install/core.entity_form_display.node.stanford_person.default.yml
  config/install/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/install/core.entity_view_display.node.stanford_person.default.yml
  config/install/core.entity_view_display.node.stanford_person.teaser.yml
  config/install/field.field.node.stanford_person.su_person_academic_appt.yml
  config/install/field.field.node.stanford_person.su_person_admin_appts.yml
  config/install/field.field.node.stanford_person.su_person_scholarly_interests.yml
  config/install/field.storage.node.su_person_academic_appt.yml
  config/install/field.storage.node.su_person_admin_appts.yml
  config/install/field.storage.node.su_person_scholarly_interests.yml
  config/install/views.view.stanford_person.yml
  dist/css/stanford_person.node.css
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.node.scss
  lib/scss/stanford_person.views.scss
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person_importer/stanford_person_importer.info.yml
  stanford_person.info.yml
  templates/sections/section-person-body-two-column.html.twig
Labels: frontend, patch, size/s

#118 D8CORE-2470 Use the default image on any imported content without an image
  modules/stanford_person_importer/stanford_person_importer.module
  modules/stanford_person_importer/stanford_person_importer.post_update.php
Labels: backend, size/xs

#117 D8CORE-2829: removing the white from the the icon
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
Labels: frontend, size/xs

#119 Adjusted the person importer to update the media item correctly
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person_importer/stanford_person_importer.info.yml
Labels: patch, size/xs

#120 D8CORE-2664: Delete 1x1 profile images and invalidate the content to reimport
  modules/stanford_person_importer/stanford_person_importer.post_update.php
Labels: backend, size/xs

#121 D8CORE-2002: unset "required" attribute on interests and affiliations field group.
  config/install/core.entity_form_display.node.stanford_person.default.yml
Labels: backend, frontend, patch, size/xs
