Repository SU-SWS/stanford_person, pull requests merged in 2020-07, with the labels that each got.

#98 D8CORE-2007: removing the span as a wrapper
  config/install/views.view.stanford_person_terms.yml
Labels: size/xs

#95 D8CORE-2228: adding the nav and aria tag so menu show in Landmarks menu
  templates/block/block--menu-block--person-type.html.twig
Labels: frontend, size/xs

#99 "8.x-1.x > 8.1.2
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_person.default.yml
  config/install/field.field.node.stanford_person.su_person_first_name.yml
  config/install/field.field.node.stanford_person.su_person_last_name.yml
  config/install/field.field.node.stanford_person.su_person_photo.yml
  config/install/field.field.node.stanford_person.su_person_profile_link.yml
  config/install/field.field.node.stanford_person.su_person_short_title.yml
  config/install/field.storage.node.su_person_profile_link.yml
  config/install/views.view.stanford_person_terms.yml
  content/file/4d5dde7e-f2c7-4d27-8ad1-99623b1308f8.json
  content/media/a4660e7f-d4bf-4a28-8030-9dc8576b1c9a.json
  dist/css/stanford_person.views.css
  lib/assets/img/stanford-person-default-profile-image.png
  lib/scss/stanford_person.views.scss
  modules/stanford_person_importer/stanford_person_importer.info.yml
  stanford_person.info.yml
  stanford_person.install
  stanford_person.module
  stanford_person.post_update.php
  templates/block/block--menu-block--person-type.html.twig
  tests/codeception/acceptance/StanfordPersonCest.php
Labels: backend, frontend, patch, size/s

#92 D8CORE-2003: change <figure> to <div>.
  templates/sections/section-person-quote.html.twig
Labels: frontend, size/xs

#101 DEVOPS-000: Missing image on install
  CHANGELOG.md
  modules/stanford_person_importer/stanford_person_importer.info.yml
  stanford_person.info.yml
  stanford_person.install
  stanford_person.module
  templates/sections/section-person-quote.html.twig
Labels: backend, frontend, patch, size/xs

#102 Removed views_taxonomy_term_name_depth thats not used
  composer.json
Labels: size/xs
