Repository SU-SWS/stanford_person, pull requests merged in 2020-05, with the labels that each got.

#85 D8CORE-000: Remove duplicated layout.
  config/install/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
  config/install/page_manager.page_variant.stanford_person_list-layout_builder-1.yml
Labels: size/s

#87 added xmlsitemap and metatag configs for optional
  README.md
  config/optional/metatag.metatag_defaults.node__stanford_person.yml
  config/optional/metatag.metatag_defaults.page_variant__stanford_person_list-layout_builder-1.yml
  config/optional/rabbit_hole.behavior_settings.node_type_stanford_person.yml
  config/optional/xmlsitemap.settings.node.stanford_person.yml
  config/optional/xmlsitemap.settings.taxonomy_term.stanford_person_types.yml
Labels: size/xs

#88 D8CORE-1969: Codeception Tests For Person
  tests/codeception/acceptance/StanfordPersonCest.php
Labels: backend, size/xs

#89 8.1.0
  CHANGELOG.md
  README.md
  composer.json
  stanford_person.info.yml
Labels: patch, size/xs

#90 back to dev
  stanford_person.info.yml
Labels: patch, size/xs
