Repository SU-SWS/stanford_person, pull requests merged in 2020-09, with the labels that each got.

#107 D8CORE-2535: Change sort on interior pages to be by last name then first
  config/install/views.view.stanford_person_list_terms_first.yml
Labels: size/xs

#108 "8.x-1.x > 8.1.5
  CHANGELOG.md
  composer.json
  config/install/views.view.stanford_person_list_terms_first.yml
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
  stanford_person.info.yml
Labels: backend, patch, size/xs

#109 Fix composer requirements
  composer.json
Labels: patch, size/xs

#110 CAP-52 Map 4 more fields from cap API
  config/install/core.entity_form_display.node.stanford_person.default.yml
  config/install/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/install/core.entity_view_display.node.stanford_person.default.yml
  config/install/core.entity_view_display.node.stanford_person.teaser.yml
  config/install/field.field.node.stanford_person.su_person_academic_appt.yml
  config/install/field.field.node.stanford_person.su_person_admin_appts.yml
  config/install/field.field.node.stanford_person.su_person_scholarly_interests.yml
  config/install/field.storage.node.su_person_academic_appt.yml
  config/install/field.storage.node.su_person_admin_appts.yml
  config/install/field.storage.node.su_person_scholarly_interests.yml
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
Labels: size/s

#111 D8CORE-2349: updating person list view to a single link
  config/install/views.view.stanford_person.yml
Labels: size/xs

#113 D8CORE-2185: matching the people edit button to the same as news
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs

#112 D8CORE-2651: adding spacing below filter menu so does not touch
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs

#115 D8CORE-2650: Fixing the spacing on the node for SOE and Basic
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
Labels: frontend, size/xs

#114 D8CORE-2531: Fixing the header for the people node
  config/install/core.entity_view_display.node.stanford_person.default.yml
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
  templates/sections/section-person-body-two-column.html.twig
Labels: frontend, size/xs
