Repository SU-SWS/stanford_person, pull requests merged in 2020-11, with the labels that each got.

#123 "8.x-1.x 8.1.8
  CHANGELOG.md
  config/install/core.entity_form_display.node.stanford_person.default.yml
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
  modules/stanford_person_importer/config/install/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person_importer/stanford_person_importer.module
  modules/stanford_person_importer/stanford_person_importer.post_update.php
  stanford_person.info.yml
Labels: backend, frontend, patch, size/s

#125 Update tests for D9 phpunit
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
Labels: backend, size/xs

#124 D8CORE-2851: fixup for the person node col.
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
Labels: frontend, size/xs

#126 Updated default content module
  .gitignore
  composer.json
  content/block_content/fb905cf3-4bd3-4bcd-ad01-92d25e46ba32.json
  content/block_content/fb905cf3-4bd3-4bcd-ad01-92d25e46ba32.yml
  content/file/433e17b4-e705-4448-9467-93a03222e3f7.json
  content/file/433e17b4-e705-4448-9467-93a03222e3f7.yml
  content/file/4d5dde7e-f2c7-4d27-8ad1-99623b1308f8.json
  content/file/4d5dde7e-f2c7-4d27-8ad1-99623b1308f8.yml
  content/media/381f792e-24b4-4c50-b5cc-69c13702f93a.json
  content/media/381f792e-24b4-4c50-b5cc-69c13702f93a.yml
  content/media/a4660e7f-d4bf-4a28-8030-9dc8576b1c9a.json
  content/media/a4660e7f-d4bf-4a28-8030-9dc8576b1c9a.yml
  content/menu_link_content/a5f9f185-b376-4cab-b3bd-dc3b03617cea.json
  content/menu_link_content/a5f9f185-b376-4cab-b3bd-dc3b03617cea.yml
  content/node/6df8090b-5dca-4386-9d72-d86e0156c0a9.json
  content/node/6df8090b-5dca-4386-9d72-d86e0156c0a9.yml
  content/paragraph/01072cf4-793d-4262-8182-b44be7287951.json
  content/paragraph/01072cf4-793d-4262-8182-b44be7287951.yml
  content/paragraph/3e8e3b0e-7803-4713-9f37-7c479f9b3365.json
  content/paragraph/3e8e3b0e-7803-4713-9f37-7c479f9b3365.yml
  content/paragraph/bd2273a4-e1f0-4fee-81b9-e98442529610.json
  content/paragraph/bd2273a4-e1f0-4fee-81b9-e98442529610.yml
  content/taxonomy_term/09700e40-34cd-4168-83f0-f9831651077e.json
  content/taxonomy_term/09700e40-34cd-4168-83f0-f9831651077e.yml
  content/taxonomy_term/0d6e3ecd-f7f4-42c7-adc3-af48af999924.json
  content/taxonomy_term/0d6e3ecd-f7f4-42c7-adc3-af48af999924.yml
  content/taxonomy_term/3f0dfa42-d32c-45e6-a984-493fd8a1a56c.json
  content/taxonomy_term/3f0dfa42-d32c-45e6-a984-493fd8a1a56c.yml
  content/taxonomy_term/55a7e336-c9d8-4fa6-8d2e-b9ec04600d26.json
  content/taxonomy_term/55a7e336-c9d8-4fa6-8d2e-b9ec04600d26.yml
  content/taxonomy_term/684cfe9e-80a2-42ec-987f-e99015d00a3e.json
  content/taxonomy_term/684cfe9e-80a2-42ec-987f-e99015d00a3e.yml
  content/taxonomy_term/6e9c4b16-655e-49f2-b737-9c5421cba82a.json
  content/taxonomy_term/6e9c4b16-655e-49f2-b737-9c5421cba82a.yml
  content/taxonomy_term/7bdb1a78-0933-4c45-b774-ab04f9891322.json
  content/taxonomy_term/7bdb1a78-0933-4c45-b774-ab04f9891322.yml
  content/taxonomy_term/81a712e0-b40f-4ffa-9152-2f97495ca730.json
  content/taxonomy_term/81a712e0-b40f-4ffa-9152-2f97495ca730.yml
  content/taxonomy_term/a6f8bcd2-3334-4ce9-aaf4-d23be467eb21.json
  content/taxonomy_term/a6f8bcd2-3334-4ce9-aaf4-d23be467eb21.yml
  content/taxonomy_term/df47c78b-8710-48de-9712-f45b0cf65a27.json
  content/taxonomy_term/df47c78b-8710-48de-9712-f45b0cf65a27.yml
  content/taxonomy_term/eece3edf-8823-419e-b1ff-8e622eb43bc2.json
  content/taxonomy_term/eece3edf-8823-419e-b1ff-8e622eb43bc2.yml
  content/taxonomy_term/f3bb3c7a-90ee-42af-ae38-381a502bb30c.json
  content/taxonomy_term/f3bb3c7a-90ee-42af-ae38-381a502bb30c.yml
  content/taxonomy_term/f836a02f-19a1-4455-ba6b-1d46fa3fcc90.json
  content/taxonomy_term/f836a02f-19a1-4455-ba6b-1d46fa3fcc90.yml
  content/taxonomy_term/fc64801e-2194-4755-9de3-38b982117dcf.json
  content/taxonomy_term/fc64801e-2194-4755-9de3-38b982117dcf.yml
  stanford_person.info.yml
Labels: frontend, patch, size/xl
