Repository SU-SWS/stanford_person, pull requests merged in 2020-08, with the labels that each got.

#103 D8ORE-2368 D8CORE-2367: fixing spacing on the people node
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
Labels: frontend, size/xs

#104 "8.x-1.x > 8.1.4
  CHANGELOG.md
  composer.json
  dist/css/stanford_person.node.css
  lib/scss/stanford_person.node.scss
  modules/stanford_person_importer/stanford_person_importer.info.yml
  stanford_person.info.yml
Labels: frontend, patch, size/xs

#106 D8CORE-000 Adjusted regext to retain numbers in workgroups and org codes
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
Labels: backend, size/xs
