Repository SU-SWS/stanford_person, pull requests merged in 2021-01, with the labels that each got.

#130 Updated circleci testing
  .circleci/config.yml
  composer.json
Labels: ci, size/xs

#131 Pass the ps parameter when alot of sunets are to be imported
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
Labels: backend, size/xs

#132 D8CORE-2750: fixing the heading spacing
  dist/css/stanford_person.views.css
  dist/js/stanford_person.script.js
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs
