Repository SU-SWS/stanford_person, pull requests merged in 2021-02, with the labels that each got.

#133 D8CORE-3452: removing extra space when putting the view in a paragraph list
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs

#134 "8.x-1.x 8.1.10
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  dist/css/stanford_person.views.css
  dist/js/stanford_person.script.js
  lib/scss/stanford_person.views.scss
  modules/stanford_person_importer/src/Cap.php
  modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person_importer/tests/src/Unit/CapTest.php
  stanford_person.info.yml
Labels: backend, ci, frontend, patch, size/s

#135 D8CORE-3512: people list fixing
  CHANGELOG.md
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
  modules/stanford_person_importer/stanford_person_importer.info.yml
  stanford_person.info.yml
Labels: frontend, patch, size/xs

#137 D8C0RE-2954: adding a little padding between image and name
  dist/css/stanford_person.node.css
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
  package-lock.json
  package.json
Labels: frontend, size/xl
