Repository SU-SWS/stanford_person, pull requests merged in 2022-04, with the labels that each got.

#163 D8CORE-5758: updating styles to match change to a list
  composer.json
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/s

#162 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/xs

#165 D8CORE-5729: style updates
  dist/css/stanford_person.views.css
  lib/scss/stanford_person.views.scss
Labels: frontend, size/xs
